from typing import Any, Callable, List

class AsyncIOScheduler:
    running: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_job(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
    def get_jobs(self) -> List[Any]: ...
    def start(self) -> None: ...
    def shutdown(self, *args: Any, **kwargs: Any) -> None: ...
