from typing import Any

class Counter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def labels(self, *args: Any, **kwargs: Any) -> "Counter": ...
    def inc(self, *args: Any, **kwargs: Any) -> None: ...

class Histogram:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def labels(self, *args: Any, **kwargs: Any) -> "Histogram": ...
    def observe(self, *args: Any, **kwargs: Any) -> None: ...

CONTENT_TYPE_LATEST: str

def generate_latest(*args: Any, **kwargs: Any) -> bytes: ...
