"""initial schema

Revision ID: 0d6132be0bb0
Revises:
Create Date: 2025-10-28 15:07:49.522159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d6132be0bb0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=128), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "MVG_DEPARTURES", "MVG_STATIONS", "WEATHER", name="ingestion_source"
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "RETRYING",
                name="ingestion_status",
            ),
            server_default="RUNNING",
            nullable=False,
        ),
        sa.Column("records_inserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_runs_job_started",
        "ingestion_runs",
        ["job_name", "started_at"],
        unique=False,
    )
    op.create_table(
        "stations",
        sa.Column("station_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("place", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "transport_modes",
            postgresql.ARRAY(sa.String(length=32)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default="Europe/Berlin",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("station_id"),
    )
    op.create_table(
        "transit_lines",
        sa.Column("line_id", sa.String(length=32), nullable=False),
        sa.Column(
            "transport_mode",
            sa.Enum("UBAHN", "SBAHN", "TRAM", "BUS", "REGIONAL", name="transport_mode"),
            nullable=False,
        ),
        sa.Column(
            "operator", sa.String(length=64), server_default="MVG", nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("color_hex", sa.String(length=7), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("line_id"),
    )
    op.create_table(
        "departure_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.String(length=64), nullable=False),
        sa.Column("line_id", sa.String(length=32), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.String(length=255), nullable=True),
        sa.Column("destination", sa.String(length=255), nullable=True),
        sa.Column("planned_departure", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delay_seconds", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(length=16), nullable=True),
        sa.Column(
            "transport_mode",
            sa.Enum("UBAHN", "SBAHN", "TRAM", "BUS", "REGIONAL", name="transport_mode"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "on_time", "delayed", "cancelled", "unknown", name="departure_status"
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column(
            "remarks",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("crowding_level", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), server_default="mvg", nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"], ["ingestion_runs.id"], ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["transit_lines.line_id"], ondelete="restrict"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["stations.station_id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_departures_line_planned",
        "departure_observations",
        ["line_id", "planned_departure"],
        unique=False,
    )
    op.create_index(
        "ix_departures_station_planned",
        "departure_observations",
        ["station_id", "planned_departure"],
        unique=False,
    )
    op.create_table(
        "route_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("origin_station_id", sa.String(length=64), nullable=False),
        sa.Column("destination_station_id", sa.String(length=64), nullable=False),
        sa.Column(
            "requested_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "itineraries", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "mvg_status",
            sa.Enum(
                "SUCCESS",
                "NOT_FOUND",
                "RATE_LIMITED",
                "DOWNSTREAM_ERROR",
                "TIMEOUT",
                name="external_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_station_id"], ["stations.station_id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["origin_station_id"], ["stations.station_id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_route_snapshots_requested_at",
        "route_snapshots",
        ["requested_at"],
        unique=False,
        postgresql_where=sa.text("requested_at IS NOT NULL"),
    )
    op.create_table(
        "weather_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.String(length=64), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("feels_like_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("humidity_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_speed_mps", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_gust_mps", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_direction_deg", sa.Integer(), nullable=True),
        sa.Column("pressure_hpa", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("visibility_km", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("precipitation_mm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("precipitation_type", sa.String(length=32), nullable=True),
        sa.Column(
            "condition",
            sa.Enum(
                "clear",
                "cloudy",
                "rain",
                "snow",
                "storm",
                "fog",
                "mixed",
                "unknown",
                name="weather_condition",
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "alerts",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "source_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"], ["ingestion_runs.id"], ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["stations.station_id"], ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weather_location_time",
        "weather_observations",
        ["latitude", "longitude", "observed_at"],
        unique=False,
    )
    op.create_table(
        "departure_weather_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("departure_id", sa.BigInteger(), nullable=False),
        sa.Column("weather_id", sa.BigInteger(), nullable=False),
        sa.Column("offset_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.String(length=32),
            server_default="closest",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["departure_id"], ["departure_observations.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["weather_id"], ["weather_observations.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "departure_id", "weather_id", name="uq_departure_weather_unique"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("departure_weather_links")
    op.drop_index("ix_weather_location_time", table_name="weather_observations")
    op.drop_table("weather_observations")
    op.drop_index(
        "ix_route_snapshots_requested_at",
        table_name="route_snapshots",
        postgresql_where=sa.text("requested_at IS NOT NULL"),
    )
    op.drop_table("route_snapshots")
    op.drop_index("ix_departures_station_planned", table_name="departure_observations")
    op.drop_index("ix_departures_line_planned", table_name="departure_observations")
    op.drop_table("departure_observations")
    op.drop_table("transit_lines")
    op.drop_table("stations")
    op.drop_index("ix_ingestion_runs_job_started", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###

    # Drop ENUM types (not auto-generated)
    sa.Enum(name="ingestion_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ingestion_source").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="external_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="weather_condition").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="departure_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="transport_mode").drop(op.get_bind(), checkfirst=True)
