"""rename_mvg_to_transit

Revision ID: 80a6a8257627
Revises: add_gtfs_tables
Create Date: 2025-12-08 06:32:45.892337

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80a6a8257627"
down_revision: Union[str, Sequence[str], None] = "add_gtfs_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing accidental drops of GTFS tables
    # op.drop_table('gtfs_routes')
    # ... (other drops removed)

    # Manual Enum update
    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE ingestion_source ADD VALUE IF NOT EXISTS 'TRANSIT_DEPARTURES'"
        )
        op.execute(
            "ALTER TYPE ingestion_source ADD VALUE IF NOT EXISTS 'TRANSIT_STATIONS'"
        )
        # Note: We are not removing MVG values to avoid invalidating existing data history.

    # Rename column instead of drop/add to preserve data (if any)
    op.alter_column("route_snapshots", "mvg_status", new_column_name="external_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("route_snapshots", "external_status", new_column_name="mvg_status")
    # We do not downgrade enum values as Postgres does not support removing values from enums easily.

    # Re-creation of GTFS tables removed from upgrade.
    # ### end Alembic commands ###
