from typing import Any, Sequence

class Pipeline:
    def set(self, *args: Any, **kwargs: Any) -> Any: ...
    async def execute(self) -> Any: ...

class Valkey:
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *keys: str) -> Any: ...
    async def mget(self, keys: Sequence[str]) -> Any: ...
    def pipeline(self) -> Pipeline: ...

def from_url(*args: Any, **kwargs: Any) -> Valkey: ...
